- name: Configure EC2 instances
  hosts: all
  become: yes
  vars:
    timezone: "Africa/Lagos"
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Create a simple HTML page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Welcome</title></head>
          <body>
          <h1>Hello from instance {{ inventory_hostname }}</h1>
          </body>
          </html>

- name: Apply IPtables Rules
  hosts: all
  become: yes
  tasks:
    - name: Install iptables
      yum:
        name: iptables
        state: present  # or use "yum" for CentOS/RHEL based systems

    - name: Allow HTTP traffic
      iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: tcp
        destination_port: 80
